import type { TalentDefinition, TalentTree } from './types';

export const WARRIOR_TALENT_TREE_LABELS: Record<TalentTree, string> = {
  fury: 'Ataque/Furia',
  defense: 'Defesa/Sobrevivencia',
  weapons: 'Armas/Especializacao',
};

export const WARRIOR_TALENTS: readonly TalentDefinition[] = [
  {
    id: 'warrior_heavy_strikes',
    classId: 'warrior',
    name: 'Golpes Pesados',
    description: 'Aumenta dano fisico em 2% por ponto.',
    tree: 'fury',
    maxRank: 5,
    cost: 1,
    effects: [{ type: 'physical_damage_percent', valuePerRank: 2 }],
    position: { x: 0, y: 0 },
  },
  {
    id: 'warrior_combat_fury',
    classId: 'warrior',
    name: 'Furia em Combate',
    description: 'Ao acertar inimigos, pode ganhar velocidade de ataque temporaria.',
    tree: 'fury',
    maxRank: 3,
    cost: 1,
    requires: [{ talentId: 'warrior_heavy_strikes', rank: 3 }],
    effects: [{ type: 'attack_speed_proc', chancePerRank: 3, attackSpeedPercent: 10, durationSeconds: 4 }],
    position: { x: 0, y: 1 },
  },
  {
    id: 'warrior_execution',
    classId: 'warrior',
    name: 'Execucao',
    description: 'Causa mais dano em inimigos com pouca vida.',
    tree: 'fury',
    maxRank: 3,
    cost: 1,
    requires: [{ talentId: 'warrior_combat_fury', rank: 2 }],
    effects: [{ type: 'execute_damage_percent', valuePerRank: 5, enemyHpBelowPercent: 30 }],
    position: { x: 0, y: 2 },
  },
  {
    id: 'warrior_iron_skin',
    classId: 'warrior',
    name: 'Pele de Ferro',
    description: 'Aumenta armadura em 3% por ponto.',
    tree: 'defense',
    maxRank: 5,
    cost: 1,
    effects: [{ type: 'armor_percent', valuePerRank: 3 }],
    position: { x: 0, y: 0 },
  },
  {
    id: 'warrior_battle_endurance',
    classId: 'warrior',
    name: 'Resistencia de Batalha',
    description: 'Aumenta vida maxima em 2% por ponto.',
    tree: 'defense',
    maxRank: 5,
    cost: 1,
    requires: [{ talentId: 'warrior_iron_skin', rank: 2 }],
    effects: [{ type: 'max_hp_percent', valuePerRank: 2 }],
    position: { x: 0, y: 1 },
  },
  {
    id: 'warrior_last_stand',
    classId: 'warrior',
    name: 'Ultimo Folego',
    description: 'Com vida baixa, reduz dano recebido.',
    tree: 'defense',
    maxRank: 1,
    cost: 1,
    requires: [{ talentId: 'warrior_battle_endurance', rank: 3 }],
    effects: [{ type: 'low_hp_damage_reduction', value: 30, hpBelowPercent: 25 }],
    position: { x: 0, y: 2 },
  },
  {
    id: 'warrior_sword_mastery',
    classId: 'warrior',
    name: 'Mestre das Espadas',
    description: 'Aumenta dano com espada em 2% por ponto.',
    tree: 'weapons',
    maxRank: 5,
    cost: 1,
    effects: [{ type: 'sword_damage_percent', valuePerRank: 2 }],
    position: { x: 0, y: 0 },
  },
  {
    id: 'warrior_flame_strike',
    classId: 'warrior',
    name: 'Golpe Flamejante',
    description: 'Adiciona dano de fogo aos golpes com espada.',
    tree: 'weapons',
    maxRank: 3,
    cost: 1,
    requires: [{ talentId: 'warrior_sword_mastery', rank: 3 }],
    effects: [{ type: 'fire_damage_on_hit', valuePerRank: 4 }],
    position: { x: 0, y: 1 },
  },
  {
    id: 'warrior_brutal_precision',
    classId: 'warrior',
    name: 'Precisao Brutal',
    description: 'Aumenta chance critica em 5% por ponto.',
    tree: 'weapons',
    maxRank: 3,
    cost: 1,
    requires: [{ talentId: 'warrior_flame_strike', rank: 2 }],
    effects: [{ type: 'critical_chance_percent', valuePerRank: 5 }],
    position: { x: 0, y: 2 },
  },
];

export const WARRIOR_TALENT_BY_ID = Object.fromEntries(WARRIOR_TALENTS.map((talent) => [talent.id, talent])) as Record<string, TalentDefinition>;
